In [2]:
import numpy as np

In [27]:
A = np.array([[2,1,4],[2,2,5],[1,1,1]])

In [48]:
print(A)
print(np.delete(A,(1),axis=0, (1), axis=1))
print(np.delete(A,(1),axis=1))

SyntaxError: positional argument follows keyword argument (3321870390.py, line 2)

In [54]:
np.ones((2,2))*2

array([[2., 2.],
       [2., 2.]])

In [60]:
mean = np.array([1,2])
variance = np.array([[ 1, 1], [1, 2 ]])
print(np.random.multivariate_normal(mean, variance))

[1.07778171 3.52807416]


In [62]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [67]:
np.ones((2,1))[0][0]

1.0

In [68]:
A = np.ones((2,2))
b = np.ones(2)
A.dot(b)

array([2., 2.])

In [69]:
A

array([[1., 1.],
       [1., 1.]])

In [73]:
np.multiply(A,3)

array([[3., 3.],
       [3., 3.]])

In [82]:
def _A(A, i, j):
    B = np.delete(A, (i), axis=0)
    B = np.delete(B, (j), axis=1)
    return B
A = np.ones((2,2))
np.linalg.det(_A(A, 1, 1))

1.0

In [84]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [86]:
A.shape

(2, 2)

In [ ]:
n